### PR TITLE
Fix timeout configuration

### PR DESCRIPTION
**Pull request by kyungeonchoi**
- Set timeout in the `ExponentialRetry` than client methods such as `post`

### CODE REVIEW

**Review by BenGalewsky — APPROVED** [review]
🥂

**Comment by BenGalewsky** [comment]
Oops, broken tests

**Comment by kyungeonchoi** [comment]
> Oops, broken tests

Interesting - it passes local tests :) Let me have a look

**Comment by ponyisi** [comment]
> > Oops, broken tests
> 
> Interesting - it passes local tests :) Let me have a look

This is some kind of cache db locking problem ...

**Comment by kyungeonchoi** [comment]
Let me merge as it passes all tests

**Pull request merged**
