### PR TITLE
Get config information from servicex.yaml and servicex.yml and .servicex files

### PR DESCRIPTION
**Pull request by gordonwatts**
With this PR, the frontend will search for config information in a `servicex.yaml`, `servicex.yml`, and `.servicex` file.

### CODE REVIEW

**Review by AndrewEckart — APPROVED** [review]
What happens when more than one of `.servicex`, `servicex.yaml`, and `servicex.yml` are present? I tested and it seems that `servicex.yaml` takes precedence over `.servicex`, at least in the local directory. Maybe this is related to the ordering of the calls to `_add_from_path`? If so, the ordering should be consist and the docs should reflect it.

If supporting multiple filenames is undesirably complex, my suggestion would be that we deprecate `.servicex` and support only `servicex.yaml` moving forward (I believe the `.yml` extension has been discouraged for a while). While we'd lose the "hidden" behavior of the dot prefix, this would be a bit simpler; YAML files are widely used for configuration, and our current userbase is small enough for the impact of a breaking change to be minimal.

That said, I'm happy with keeping 2 or 3 reserved filenames, as long as it's clear which one will be used first. The YAML parsing seems to be working great.

**Comment by gordonwatts** [comment]
Thanks for looking. I'll update the docs to reflect the ordering explicit. It was done that way on purpose, actually - Make sure the "visible" file has precedence over the "invisible" file. That makes debugging a little easier - one less thing to think about.

I'll keep both yml and yaml - I see both around.

I'll keep the hidden file. One's Linux home directory is already cluttered enough without having to liter it with config files. It seems like it is the standard for linux tools anyway.

**Comment by AndrewEckart** [comment]
> Thanks for looking. I'll update the docs to reflect the ordering explicit. It was done that way on purpose, actually - Make sure the "visible" file has precedence over the "invisible" file. That makes debugging a little easier - one less thing to think about.
> 
> I'll keep both yml and yaml - I see both around.
> 
> I'll keep the hidden file. One's Linux home directory is already cluttered enough without having to liter it with config files. It seems like it is the standard for linux tools anyway.

Great - my suggestion is that the ordering between `.yaml` and `.yml` on lines 24-25 and 37-38 should be the same (probably `.yaml` before `.yml`). Thanks for the quick turnaround!

**Comment by gordonwatts** [comment]
Ok! I'll later that. As far as quick turn around... given when you submitted this bugreport, I'd not call this quick! :-)

**Pull request merged**
