### PR TITLE
Upgrade to pydantic2

### PR DESCRIPTION
**Pull request by BenGalewsky**
# Background
Pydantic V2 is a ground-up rewrite that offers many new features, performance improvements, and some breaking changes compared to Pydantic V1. The main reasons for the changes include:
- Significant performance improvements: Based on benchmarks, Pydantic v[2](https://pypi.org/project/pydantic/2.0.1/) is between 4x and 50x faster than Pydantic v1.
- Improved reliability and consistency: Pydantic v2 offers a strict mode that no longer magically coerces data, clear rules on required vs nullable fields, and more flexible validation options.
- New features: Pydantic V2 introduces many new features, such as support for autocomplete in VS Code via dataclass_transform.
- Breaking changes: While the transition to Pydantic V2 requires some breaking changes, the changes are not so numerous or game-changing that they cannot be understood by reading the documentation. The migration guide and new API docs provide detailed information on the changes between V1 and V[2](https://pypi.org/project/pydantic/2.0.1/).
- Maintainability: The aggressive removals between major versions are likely better for maintainability, considering Pydantic's complexity and the fact that it was basically a rewrite

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Resolves https://github.com/ssl-hep/ServiceX_frontend/issues/363

**Review by kyungeonchoi — APPROVED** [review]
Working nicely!

**Comment by matthewfeickert** [comment]
Once this is merged in, can a `3.0.0-alpha.16` release please be made as well? I can use that to update the `AB-dev` container images.

**Comment by kyungeonchoi** [comment]
@matthewfeickert - if you are referring to the ServiceX client version in the [ATLAS idap repo](https://github.com/iris-hep/idap-200gbps-atlas/blob/main/requirements.txt) that's still in the another branch (`3.0_develop_uprootraw`). It includes some refactoring so we are planning to merge after having a discussion during the coming ServiceX chat :)

**Comment by matthewfeickert** [comment]
> if you are referring to the ServiceX client version in the [ATLAS idap repo](https://github.com/iris-hep/idap-200gbps-atlas/blob/main/requirements.txt)

More broadly than the repo but https://github.com/iris-hep/idap-200gbps-atlas/issues/60 in general with the servicex client getting added to the install list in https://github.com/usatlas/analysisbase-dask.

> that's still in the another branch (`3.0_develop_uprootraw`). It includes some refactoring so we are planning to merge after having a discussion during the coming ServiceX chat

I guess I'm confused about how development is done here, but that branch is a separate feature request, so why isn't that branch just rebased off of `3.0_develop` and updated to the new version after this is merged in?

**Comment by matthewfeickert** [comment]
Thanks @BenGalewsky, for the great PR and for merging this in!

@kyungeonchoi I'm sorry earlier for writing a note hastily and without proper clarity. I didn't mean to suggest that a alpha release be cut from the `3.0_develop_uprootraw` branch (until `3.0_develop` is merged into `main` with the `3.0` release I assume that all alpha and rcs will be cut from the `3.0_develop` branch). I had misunderstood

> It includes some refactoring so we are planning to merge after having a discussion during the coming ServiceX chat 

to mean that you were waiting on `3.0_develop_uprootraw` to merge it into this PR's branch. But I understand that I was mistaken now, and if I attended the serviceX meetings I probably wouldn't be.

I can't promise that I'll be at the Friday 2024-05-03 meeting, but if the `3.0_develop_uprootraw` branch isn't ready to PR tomorrow would it still be possible to make another alpha release now that this PR is in?

**Pull request merged**
